apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: opaque
data: 
    mongo-root-username: dXNlcm5hbWU= # Base64-encoded value for the MongoDB root username
    mongo-root-password: cGFzc3dvcmQ= # Base64-encoded value for the MongoDB root password

